Repository WooGie911/Moving_FE, pull requests merged in 2025-07, with the labels that each got.

#2 chore: 템플릿 테스트
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 지연, chore

#9 [#6]feat:chip 공용컴포넌트 개발
  src/app/globals.css
  src/components/common/Chips/CircleTextLabel.tsx
  src/components/common/Chips/MoveTypeLabel.tsx
  src/hooks/useMediaQuery.ts
Labels: 수빈, feat, priority: high, done

#11 [#8]feat: 버튼 공용 컴포넌트 구현
  src/app/globals.css
  src/components/common/button/Button.tsx
Labels: 지연, feat, priority: high, ready for review

#15 [#6]chore:chip 컴포넌트 반응형 수정 및 글로벌CSS브레이크 포인트 정의
  src/app/globals.css
  src/components/common/Chips/CircleTextLabel.tsx
  src/components/common/Chips/MoveTypeLabel.tsx
  src/hooks/useMediaQuery.ts
Labels: 수빈, chore, done

#17 [#14] feat: 공용 컴포넌트 찜 버튼 구현
  src/components/common/button/Button.tsx
  src/hooks/useLikeToggle.ts
  src/types/button.ts
Labels: 지연, feat, ready for review

#18 [#12] feat : tab 공용 컴포넌트 구현
  src/app/layout.tsx
  src/components/common/gnb/Gnb.tsx
  src/components/common/gnb/GnbActions.tsx
  src/components/common/gnb/Logo.tsx
  src/components/common/gnb/LogoAndTab.tsx
  src/components/common/gnb/SideGnb.tsx
  src/components/common/tab/Tab.tsx
  src/hooks/useWindowWidth.ts
  src/pages/landing/LadingPage.tsx
Labels: 민규, feat, ready for review

#19 [#6]refactor :타입 위치 통일 및 4중삼항 제거 피드백반영
  src/app/page.tsx
  src/components/common/Chips/CircleTextLabel.tsx
  src/components/common/Chips/MoveTypeLabel.tsx
Labels: 수빈, refactor

#31 chore : 최상위 컴포넌트 폴더에 각 도메인에 대한 폴더 추가
  src/components/auth/.gitkeep
  src/components/auth/signin/.gitkeep
  src/components/auth/signup/.gitkeep
  src/components/estimate/.gitkeep
  src/components/estimate/list/.gitkeep
  src/components/estimate/list/mover/(myEstimate)/.gitkeep
  src/components/estimate/list/mover/(myEstimate)/rejected/.gitkeep
  src/components/estimate/list/mover/(myEstimate)/rejected/[id]/.gitkeep
  src/components/estimate/list/mover/(myEstimate)/requested/.gitkeep
  src/components/estimate/list/mover/(myEstimate)/requested/[id]/.gitkeep
  src/components/estimate/list/mover/.gitkeep
  src/components/estimate/list/mover/received/.gitkeep
  src/components/estimate/list/user/received/.gitkeep
  src/components/estimate/list/user/received/[id]/.gitkeep
  src/components/estimate/list/user/waiting/.gitkeep
  src/components/estimate/list/user/waiting/[id]/.gitkeep
  src/components/estimate/request/.gitkeep
  src/components/favoriteMover/.gitkeep
  src/components/landing/.gitkeep
  src/components/profile/.gitkeep
  src/components/profile/edit/.gitkeep
  src/components/profile/register/.gitkeep
  src/components/review/.gitkeep
  src/components/review/writable/.gitkeep
  src/components/review/written/.gitkeep
  src/components/searchMover/.gitkeep
  src/components/searchMover/[id]/.gitkeep
  src/pages/auth/signin/page.tsx
  src/pages/auth/signup/page.tsx
Labels: 민규, chore, priority: critical

#33 feat/commonComponent-input 리액트 훅 폼 라이브러리를 활용해 인풋 공용 컴포넌트 개발.
  package-lock.json
  package.json
  src/app/globals.css
  src/assets/icon/etc/icon-search-lg.png
  src/assets/icon/etc/icon-search.png
  src/components/common/input/BaseInput.tsx
  src/components/common/input/PasswordInput.tsx
  src/components/common/input/SearchInput.tsx
  src/components/common/input/TextAreaInput.tsx
  src/components/common/input/TextInput.tsx
Labels: 재욱, feat, priority: high

#47 [#46]feat:견적 요청에서 사용되는 주소 컴포넌트 구현
  src/app/globals.css
  src/components/common/card/AddressCard.tsx
Labels: 승준, feat

#51 [#49] fix: 버튼 컴포넌트 사이즈 props 추가
  src/components/common/button/Button.tsx
  src/types/button.ts
Labels: 지연, fix, priority: critical

#50 [#32]feat:유저-대기중인 견적 페이지 UI 구현(진행중)
  src/app/estimate/list/mover/(myEstimate)/rejected/[id]/page.tsx
  src/app/estimate/list/mover/(myEstimate)/rejected/page.tsx
  src/app/estimate/list/mover/(myEstimate)/requested/[id]/page.tsx
  src/app/estimate/list/mover/(myEstimate)/requested/page.tsx
  src/app/estimate/list/user/received/[id]/page.tsx
  src/app/estimate/list/user/received/page.tsx
  src/app/estimate/list/user/waiting/[id]/page.tsx
  src/app/estimate/list/user/waiting/page.tsx
  src/components/common/button/Button.tsx
  src/components/common/chips/CircleTextLabel.tsx
  src/components/common/chips/MoveTypeLabel.tsx
  src/components/common/tab/Tab.tsx
  src/components/estimate/list/ListTab.tsx
  src/components/estimate/list/user/CardList.tsx
  src/components/estimate/list/user/waiting/RequestQuote.tsx
  src/pages/estimate/list/mover/(myEstimate)/rejected/MoverRejectedEstimatesPage.tsx
  src/pages/estimate/list/mover/(myEstimate)/rejected/[id]/MoverRejectedEstimateDetailPage.tsx
  src/pages/estimate/list/mover/(myEstimate)/rejected/[id]/page.tsx
  src/pages/estimate/list/mover/(myEstimate)/rejected/page.tsx
  src/pages/estimate/list/mover/(myEstimate)/requested/MoverRequestedEstimatesPage.tsx
  src/pages/estimate/list/mover/(myEstimate)/requested/[id]/MoverRequestedEstimateDetailPage.tsx
  src/pages/estimate/list/mover/(myEstimate)/requested/[id]/page.tsx
  src/pages/estimate/list/mover/(myEstimate)/requested/page.tsx
  src/pages/estimate/list/user/received/ReceivedEstimatesPage.tsx
  src/pages/estimate/list/user/received/[id]/UserReceivedEstimateDetailPage.tsx
  src/pages/estimate/list/user/received/[id]/page.tsx
  src/pages/estimate/list/user/received/page.tsx
  src/pages/estimate/list/user/waiting/WaitingEstimatesPage.tsx
  src/pages/estimate/list/user/waiting/[id]/page.tsx
  src/pages/estimate/list/user/waiting/page.tsx
Labels: 수빈, feat, chore

#67 [#25] Feat/commonComponent-input-fix PasswordInput visible 반대 오류 해결.
  src/components/common/input/PasswordInput.tsx
Labels: 재욱, fix, priority: medium

#62 [#38]feat:공용 컴포넌트 모달 제작
  src/app/providers.tsx
  src/components/common/modal/ModalContext.tsx
  src/types/modal.ts
Labels: 승준, feat, priority: high

#68 [#65]feat:이사 유형 카드 컴포넌트 제작
  src/components/common/card/MovingTypeCard.tsx
Labels: 승준, feat

#70 [#69]fix: 주소 카드 seleted 사용으로 선택된 UI 구현
  src/components/common/card/AddressCard.tsx
Labels: 승준, fix

#83 [#79] feat: 주소 선택 버튼 컴포넌트 제작
  src/components/quote/create/ChooseAddressBtn.tsx
Labels: 승준, feat

#85 [#80]feat:진행바 제작
  src/components/quote/create/ProgressBar.tsx
Labels: 승준, feat, ready for review

#90 [#36] feat : 받았던 견적 페이지 UI 구현
  src/app/quote/(my)/received/page.tsx
  src/assets/icon/arrow/icon-dropdown-lg.png
  src/assets/icon/arrow/icon-dropdown.png
  src/components/quote/(my)/CardList.tsx
  src/components/quote/(my)/pending/RequestQuote.tsx
  src/components/quote/(my)/received/EstimateListSection.tsx
  src/components/quote/(my)/received/QuoteAndEstimates.tsx
  src/components/quote/(my)/received/QuoteInfo.tsx
  src/pages/quote/(my)/pending/UserPendingQuotePage.tsx
  src/pages/quote/(my)/received/UserReceivedQuotePage.tsx
  src/pages/quote/(my)/received/page.tsx
  src/types/userQuote.ts
Labels: 수빈, feat, refactor

#91 [#89]feat: 견적요청에 사용되는 달력 api 구현
  src/components/quote/create/Calendar.tsx
Labels: 승준, feat, ready for review

#96 [#26] feat : 일반 로그인 api 연결 및 테스트, 데브네비게이션 간편 로그인 및 로그인 전역 상태관리 적용
  src/components/common/DevNavitgation.tsx
  src/hooks/useAuth.ts
  src/lib/api/.gitkeep
  src/lib/api/auth.api.ts
  src/pages/auth/moverSignin/MoverSigninPage.tsx
  src/pages/auth/userSignin/UserSigninPage.tsx
  src/stores/authStore .ts
Labels: 민규, feat, priority: high

#113 [#107] feat:기사님 찾기 api 연결
  src/app/globals.css
  src/app/searchMover/page.tsx
  src/assets/icon/arrow/icon-down.png
  src/assets/icon/arrow/icon-up.png
  src/assets/img/landing/explain-img-lg.png
  src/assets/img/mascot/profile-lg.png
  src/assets/img/mascot/profile-sm.png
  src/hooks/useLikeToggle.ts
  src/lib/api/findMover.api.ts
  src/lib/utils/moverStaticData.ts
  src/lib/utils/regionMapping.ts
  src/pages/landing/LadingPage.tsx
  src/pages/searchMover/SearchMoverPage.tsx
  src/stores/searchMoverStore.ts
Labels: 지연, feat

#114 [#111]feat:견적요청 수정 삭제 페이지 제작
  src/app/quote/create/page.tsx
  src/components/common/modal/ModalContext.tsx
  src/components/quote/QuotePageWrapper.tsx
  src/components/quote/create/SpeechBubble.tsx
  src/components/quote/create/card/AddressSearchDaum.tsx
  src/messages/en.json
  src/messages/ko.json
  src/messages/zh.json
  src/pages/quote/create/QuoteCreatePage.tsx
  src/pages/quote/edit/QuoteEditPage.tsx
  src/services/quoteService.ts
  src/types/modal.ts
  src/types/quote.ts
Labels: 승준, feat, priority: critical, ready for review

#120 feat:기본 정보 수정 페이지 UI 및 유효성 검사 구현
  src/app/moverMyPage/edit/page.tsx
  src/components/common/Pagination/PaginationEllipsis.tsx
  src/components/common/Pagination/index.tsx
  src/pages/moverMyPage/edit/EditPage.tsx
  src/pages/moverMyPage/edit/page.tsx
  src/types/user.ts
Labels: 세준, feat

#119 [#116] feat/견적-기사 api작성
  src/lib/api/README.md
  src/lib/api/moverEstimate.ts
  src/pages/quote/(my)/pending/UserPendingQuotePage.tsx
  src/types/moverEstimate.ts
Labels: 수빈, priority: high

#123 [#122] fix: getUser 비회원 오류 해결
  src/providers/AuthProvider.tsx
Labels: 지연, fix

#134 feat:프로필 및 알림 드롭다운 제작
  src/app/globals.css
  src/components/common/dropdown/UserActionDropdown.tsx
Labels: 승준, feat, priority: critical

#132 feat: 기사님 마이페이지 수정 UI 및 기능 구현
  src/app/profile/edit/page.tsx
  src/components/common/input/BaseInput.tsx
  src/pages/profile/edit/ProfileEditPage.tsx
  src/pages/profile/edit/page.tsx
Labels: 세준, feat

#135 [#40] feat: 견적 기사님받은견적페이지UI구현
  src/app/estimate/received/page.tsx
  src/assets/icon/arrow/icon-arrow.png
  src/components/common/chips/CircleTextLabel.tsx
  src/components/common/input/Checkbox.tsx
  src/components/common/modal/ModalContext.tsx
  src/components/common/tab/QuoteAndEstimateTab.tsx
  src/components/estimate/.gitkeep
  src/components/estimate/CardList.tsx
  src/components/estimate/LabelArea.tsx
  src/components/estimate/received/.gitkeep
  src/components/estimate/received/Dropdown.tsx
  src/components/estimate/received/FilterAndSearchSection.tsx
  src/components/estimate/received/ModalChild.tsx
  src/components/estimate/received/PcFillterSection.tsx
  src/components/estimate/received/SelectCheckBox.tsx
  src/components/estimate/received/SelectMovinType.tsx
  src/components/estimate/received/SmallFilterSection.tsx
  src/lib/api/customerQuote.ts
  src/pages/estimate/received/MoverReceivedPage.tsx
  src/pages/estimate/received/page.tsx
  src/pages/moverMyPage/edit/EditPage.tsx
  src/pages/quote/(my)/pending/UserPendingQuotePage.tsx
  src/types/moverEstimate.ts
  src/utils/dateUtils.ts
  src/utils/regionMapping.ts
Labels: 수빈, feat, priority: high

#133 [#131] 코드 오류 사항 수정 및 코드 개선
  src/lib/actions/auth.actions.ts
  src/lib/api/auth.api.ts
  src/lib/api/user.api.ts
  src/pages/auth/moverSignin/MoverSigninPage.tsx
  src/pages/auth/moverSignup/MoverSignupPage.tsx
  src/pages/auth/userSignin/UserSigninPage.tsx
  src/pages/auth/userSignup/UserSignupPage.tsx
  src/providers/AuthProvider.tsx
  src/utils/auth.ts
  src/utils/validators.ts
Labels: 민규, refactor, priority: medium

#140 [#42] feat/기사-상세페이지제작
  src/components/common/button/ShareButton.tsx
  src/components/estimate/(my)/rejected/.gitkeep
  src/components/estimate/(my)/rejected/[id]/RejectDetailMain.tsx
  src/components/estimate/(my)/request/[id]/.gitkeep
  src/components/estimate/(my)/request/[id]/RequestDetailMain.tsx
  src/components/estimate/(my)/resolved/.gitkeep
  src/components/estimate/(my)/resolved/[id]/.gitkeep
  src/components/quote/(my)/DetailMoveInfo.tsx
  src/components/quote/(my)/DetailPageMainSeaction.tsx
  src/components/quote/(my)/ShareSection.tsx
  src/pages/estimate/(my)/rejected/[id]/RejectedDetailPage.tsx
  src/pages/estimate/(my)/request/[id]/RequsetDetailPage.tsx
  src/pages/quote/(my)/pending/[id]/UserPendingQuoteDetailPage.tsx
  src/types/userQuote.ts
  src/utils/shareUtils.ts
Labels: 수빈, feat, priority: high

#141 [#109] feat : 일반유저/기사님 프로필 등록 페이지 UI 구현
  src/app/profile/register/page.tsx
  src/constant/profile.ts
  src/middleware.ts
  src/pages/profile/edit/ProfileEditPage.tsx
  src/pages/profile/register/CustomerRegisterPage.tsx
  src/pages/profile/register/MoverRegisterPage.tsx
  src/pages/profile/register/page.tsx
  src/providers/AuthProvider.tsx
Labels: 민규, feat

#144 [#142] feat: 기사님 상세 컴포넌트 및 api 연결
  next.config.ts
  src/components/searchMover/[id]/Chip.tsx
  src/components/searchMover/[id]/DetailInformation.tsx
  src/components/searchMover/[id]/MoverIntro.tsx
  src/components/searchMover/[id]/RequestButton.tsx
  src/components/searchMover/[id]/ReviewAvg.tsx
  src/components/searchMover/[id]/ReviewList.tsx
  src/components/searchMover/[id]/TopBar.tsx
  src/lib/api/findMover.api.ts
  src/lib/utils/mockReviewData.ts
  src/pages/searchMover/[id]/SearchMoverDetailPage.tsx
  src/types/findMover.ts
  src/types/moverDetail.ts
Labels: 지연, feat

#146 fix:유저견적페이지리펙토링
  src/components/estimate/(my)/rejected/[id]/RejectDetailMain.tsx
  src/components/estimate/(my)/request/[id]/RequestDetailMain.tsx
  src/components/estimate/CardList.tsx
  src/components/quote/(my)/CardList.tsx
  src/components/quote/(my)/DetailMoveInfo.tsx
  src/components/quote/(my)/DetailPageMainSeaction.tsx
  src/components/quote/(my)/LabelAndTitleSection.tsx
  src/components/quote/(my)/pending/.gitkeep
  src/components/quote/(my)/pending/RequestQuote.tsx
  src/components/quote/(my)/pending/[id]/.gitkeep
  src/components/quote/(my)/received/.gitkeep
  src/components/quote/(my)/received/LastButtonSection.tsx
  src/components/quote/(my)/received/QuoteAndEstimates.tsx
  src/components/quote/(my)/received/QuoteInfo.tsx
  src/lib/api/customerQuote.ts
  src/pages/estimate/received/MoverReceivedPage.tsx
  src/pages/quote/(my)/pending/UserPendingQuotePage.tsx
  src/pages/quote/(my)/pending/[id]/UserPendingQuoteDetailPage.tsx
  src/pages/quote/(my)/received/UserReceivedQuotePage.tsx
  src/pages/quote/(my)/received/[id]/UserReceicedQuoteDetialPage.tsx
  src/types/moverEstimate.ts
  src/types/userQuote.ts
Labels: 수빈, feat, fix

#148 Feat/profile logic
  next.config.ts
  src/assets/img/etc/profile-upload-skeleton.png
  src/constant/profile.ts
  src/lib/api/user.api.ts
  src/pages/auth/moverSignin/MoverSigninPage.tsx
  src/pages/auth/moverSignup/MoverSignupPage.tsx
  src/pages/auth/userSignin/UserSigninPage.tsx
  src/pages/auth/userSignup/UserSignupPage.tsx
  src/pages/profile/register/CustomerRegisterPage.tsx
  src/pages/profile/register/MoverRegisterPage.tsx
  src/utils/validators.ts
Labels: 민규, feat, priority: medium

#145 [#95] Feat/notification 알림 기능 구현.
  src/app/notification/page.tsx
  src/app/providers.tsx
  src/components/common/dropdown/UserActionDropdown.tsx
  src/components/common/gnb/GnbActions.tsx
  src/components/notification/NotificationList.tsx
  src/lib/api/notification.api.ts
  src/providers/NotificationSSEProvider.tsx
  src/stores/notificationStore.ts
  src/types/notification.types.ts
Labels: 재욱, feat, priority: medium

#151 fix : 프로필 등록 api 호출이 로컬 url로 호출하던 문제 수정
  src/lib/api/user.api.ts
Labels: 민규

#154 [#153] feat: 기사님 기본정보 수정 API연동
  src/lib/api/user.api.ts
  src/pageComponents/moverMyPage/edit/EditPage.tsx
Labels: 세준, feat, priority: medium

#158 [#155] feat:공유하기 기능 함수 작성 및 연동
  src/app/estimate/(my)/resolved/page.tsx
  src/app/layout.tsx
  src/app/searchMover/[id]/page.tsx
  src/components/common/button/ShareButton.tsx
  src/components/common/button/ShareButtonGroup.tsx
  src/components/common/pagination/PaginationButton.tsx
  src/components/common/pagination/PaginationEllipsis.tsx
  src/components/common/pagination/index.tsx
  src/components/common/pagination/usePagination.ts
  src/components/quote/(my)/ShareSection.tsx
  src/components/quote/(my)/pending/RequestQuote.tsx
  src/components/searchMover/[id]/DetailInformation.tsx
  src/components/searchMover/[id]/ReviewList.tsx
  src/utils/shareUtils.ts
Labels: 수빈, feat

#159 [#5] 페이지네이션 컴포넌트 네이밍 수정
  src/app/searchMover/[id]/page.tsx
  src/components/common/pagination/Pagination.tsx
  src/components/searchMover/%5Bid%5D/ReviewList.tsx
  src/components/searchMover/[id]/ReviewList.tsx
  src/pageComponents/searchMover/SearchMoverDetailPage.tsx
Labels: 세준, fix, priority: high

#161 [#160] refactor : 로그인/회원가입 리팩터링
  src/app/profile/register/page.tsx
  src/components/common/DevNavitgation.tsx
  src/components/common/gnb/Gnb.tsx
  src/components/common/gnb/GnbActions.tsx
  src/constant/profile.ts
  src/lib/api/auth.api.ts
  src/lib/api/user.api.ts
  src/middleware.ts
  src/pageComponents/auth/moverSignup/MoverSignupPage.tsx
  src/pageComponents/auth/userSignin/UserSigninPage.tsx
  src/pageComponents/auth/userSignup/UserSignupPage.tsx
  src/pageComponents/profile/register/CustomerRegisterPage.tsx
  src/pageComponents/profile/register/MoverRegisterPage.tsx
  src/providers/AuthProvider.tsx
  src/types/auth.ts
  src/types/user.types.ts
  src/utils/decodeAccessToken.ts
  src/utils/validators.ts
Labels: 민규, refactor

#163 [#160] refactor : 프로필 등록 페이지 리팩터링
  src/components/common/gnb/GnbActions.tsx
  src/lib/actions/auth.actions.ts
  src/lib/api/user.api.ts
  src/middleware.ts
  src/pageComponents/profile/register/CustomerRegisterPage.tsx
  src/pageComponents/profile/register/MoverRegisterPage.tsx
  src/providers/AuthProvider.tsx
Labels: 민규

#165 [#164] fix: 견적-스키마수정에 따른 리펙토링 작업
  src/components/estimate/(my)/request/[id]/RequestDetailMain.tsx
  src/components/estimate/CardList.tsx
  src/components/estimate/LabelArea.tsx
  src/components/estimate/received/Dropdown.tsx
  src/components/estimate/received/ModalChild.tsx
  src/components/estimate/received/PcFillterSection.tsx
  src/components/quote/(my)/CardList.tsx
  src/components/quote/(my)/DetailMoveInfo.tsx
  src/components/quote/(my)/DetailPageMainSeaction.tsx
  src/components/quote/(my)/LabelAndTitleSection.tsx
  src/components/quote/(my)/LgButtonSection.tsx
  src/components/quote/(my)/MoverInfo.tsx
  src/components/quote/(my)/pending/RequestQuote.tsx
  src/components/quote/(my)/received/EstimateListSection.tsx
  src/components/quote/(my)/received/QuoteAndEstimates.tsx
  src/components/quote/(my)/received/QuoteInfo.tsx
  src/lib/api/customerEstimateRequest.ts
  src/lib/api/moverEstimate.ts
  src/pageComponents/estimate/(my)/rejected/RejectedPage.tsx
  src/pageComponents/estimate/(my)/rejected/[id]/RejectedDetailPage.tsx
  src/pageComponents/estimate/(my)/request/RequsetPage.tsx
  src/pageComponents/estimate/received/MoverReceivedPage.tsx
  src/pageComponents/quote/(my)/pending/UserPendingQuotePage.tsx
  src/pageComponents/quote/(my)/pending/[id]/UserPendingQuoteDetailPage.tsx
  src/pageComponents/quote/(my)/received/UserReceivedQuotePage.tsx
  src/pageComponents/quote/(my)/received/[id]/UserReceicedQuoteDetialPage.tsx
  src/types/customerEstimateRequest.ts
  src/types/moverEstimate.ts
  src/types/userQuote.ts
Labels: 수빈, feat, fix, priority: high

#162 [#73] refactor: 기본정보수정 리팩토링 및 passwordinput 수정
  package-lock.json
  src/components/common/input/PasswordInput.tsx
  src/pageComponents/moverMyPage/edit/EditPage.tsx
Labels: 세준, fix, priority: medium

#167 [#164] fix:토탈찜개수 추가에 따른 페이지 랜더링
  next.config.ts
  src/app/estimate/(my)/resolved/[id]/page.tsx
  src/app/estimate/(my)/resolved/page.tsx
  src/app/estimateRequest/(my)/pending/[id]/page.tsx
  src/app/estimateRequest/(my)/pending/page.tsx
  src/app/estimateRequest/(my)/received/[id]/page.tsx
  src/app/estimateRequest/(my)/received/page.tsx
  src/assets/img/etc/noEstimate.png
  src/components/common/tab/EstimateRequestAndEstimateTab.tsx
  src/components/estimate/(my)/.gitkeep
  src/components/estimate/(my)/rejected/[id]/RejectDetailMain.tsx
  src/components/estimate/CardList.tsx
  src/components/estimate/received/ModalChild.tsx
  src/components/estimateRequest/(my)/DetailMoveInfo.tsx
  src/components/estimateRequest/(my)/MoverInfo.tsx
  src/components/estimateRequest/(my)/pending/RequestEstimateRequest.tsx
  src/components/estimateRequest/(my)/received/EstimateRequestAndEstimates.tsx
  src/components/estimateRequest/(my)/received/EstimateRequestInfo.tsx
  src/lib/api/customerEstimateRequest.ts
  src/lib/api/moverEstimate.ts
  src/pageComponents/estimate/(my)/rejected/RejectedPage.tsx
  src/pageComponents/estimate/(my)/rejected/[id]/RejectedDetailPage.tsx
  src/pageComponents/estimate/(my)/request/RequsetPage.tsx
  src/pageComponents/estimate/(my)/request/[id]/RequsetDetailPage.tsx
  src/pageComponents/estimate/(my)/resolved/page.tsx
  src/pageComponents/estimate/received/MoverReceivedPage.tsx
  src/pageComponents/estimateRequest/(my)/pending/UserPendingEstimateRequestPage.tsx
  src/pageComponents/estimateRequest/(my)/pending/UserPendingQuotePage.tsx
  src/pageComponents/estimateRequest/(my)/pending/[id]/UserPendingEstimateRequestDetailPage.tsx
  src/pageComponents/estimateRequest/(my)/pending/[id]/UserPendingQuoteDetailPage.tsx
  src/pageComponents/estimateRequest/(my)/received/UserReceivedEstimateRequestPage.tsx
  src/pageComponents/estimateRequest/(my)/received/UserReceivedQuotePage.tsx
  src/pageComponents/estimateRequest/(my)/received/[id]/UserReceicedQuoteDetialPage.tsx
  src/pageComponents/estimateRequest/(my)/received/[id]/UserReceivedEstimateRequestDetailPage.tsx
  src/types/customerEstimateRequest.ts
  src/types/moverEstimate.ts
Labels: 수빈, feat, fix

#171 [#93, #94, #170] feat/review 리뷰 페이지 구현 및 리팩토링.
  src/app/review/layout.tsx
  src/app/review/writable/page.tsx
  src/app/review/written/page.tsx
  src/components/common/button/Button.tsx
  src/components/review/.gitkeep
  src/components/review/writable/.gitkeep
  src/components/review/writable/ReviewWriteModal.tsx
  src/components/review/writable/StarRating.tsx
  src/components/review/writable/WritableMoverCard.tsx
  src/components/review/writable/WritableMoverCardList.tsx
  src/components/review/written/.gitkeep
  src/components/review/written/ReviewCard.tsx
  src/components/review/written/WrittenMoverCard.tsx
  src/lib/api/review.api.ts
  src/pageComponents/review/writable/WritableReviewPage.tsx
  src/pageComponents/review/writable/page.tsx
  src/pageComponents/review/written/WrittenReviewPage.tsx
  src/pageComponents/review/written/page.tsx
  src/types/button.ts
  src/types/review.ts
Labels: 재욱, feat, priority: medium

#175 [#135] feat : 토큰 재발급 로직 적용 및 재발급 사용을 위한 래핑 함수 구현
  src/lib/actions/auth.actions.ts
  src/lib/api/auth.api.ts
  src/lib/api/fetcher.api.ts
  src/lib/api/user.api.ts
Labels: 민규, feat

#177 [#176] feat&fix : 견적 API 연동 및 리펙토링
  src/components/common/tab/EstimateRequestAndEstimateTab.tsx
  src/components/estimate/(my)/rejected/[id]/RejectDetailMain.tsx
  src/components/estimate/(my)/request/[id]/RequestDetailMain.tsx
  src/components/estimate/CardList.tsx
  src/components/estimate/received/ModalChild.tsx
  src/components/estimateRequest/(my)/CardList.tsx
  src/components/estimateRequest/(my)/DetailMoveInfo.tsx
  src/components/estimateRequest/(my)/MoverInfo.tsx
  src/components/estimateRequest/(my)/pending/RequestEstimateRequest.tsx
  src/components/estimateRequest/(my)/received/EstimateRequestInfo.tsx
  src/components/searchMover/FavoriteMoverList.tsx
  src/constant/devNavRouteGroups.ts
  src/constant/gnbItems.ts
  src/lib/api/customerEstimateRequest.ts
  src/lib/api/moverEstimate.api.ts
  src/pageComponents/estimate/(my)/rejected/RejectedPage.tsx
  src/pageComponents/estimate/(my)/rejected/[id]/RejectedDetailPage.tsx
  src/pageComponents/estimate/(my)/request/RequsetPage.tsx
  src/pageComponents/estimate/(my)/request/[id]/RequsetDetailPage.tsx
  src/pageComponents/estimate/received/MoverReceivedPage.tsx
  src/pageComponents/estimateRequest/(my)/pending/UserPendingEstimateRequestPage.tsx
  src/pageComponents/estimateRequest/(my)/pending/[id]/UserPendingEstimateRequestDetailPage.tsx
  src/pageComponents/estimateRequest/(my)/received/UserReceivedEstimateRequestPage.tsx
  src/pageComponents/estimateRequest/(my)/received/[id]/UserReceivedEstimateRequestDetailPage.tsx
  src/pageComponents/estimateRequest/create/EstimateRequestCreatePage.tsx
  src/types/customerEstimateRequest.ts
  src/utils/dateUtils.ts
Labels: 수빈, feat, fix

#179 [#178]feat: i18n을 이용하여 번역기능 구현
  next.config.ts
  package-lock.json
  package.json
  src/app/[locale]/(auth)/moverSignin/page.tsx
  src/app/[locale]/(auth)/moverSignup/page.tsx
  src/app/[locale]/(auth)/userSignin/page.tsx
  src/app/[locale]/(auth)/userSignup/page.tsx
  src/app/[locale]/estimate/(my)/rejected/[id]/page.tsx
  src/app/[locale]/estimate/(my)/rejected/page.tsx
  src/app/[locale]/estimate/(my)/request/[id]/page.tsx
  src/app/[locale]/estimate/(my)/request/page.tsx
  src/app/[locale]/estimate/received/page.tsx
  src/app/[locale]/estimateRequest/(my)/pending/[id]/page.tsx
  src/app/[locale]/estimateRequest/(my)/pending/page.tsx
  src/app/[locale]/estimateRequest/(my)/received/[id]/page.tsx
  src/app/[locale]/estimateRequest/(my)/received/page.tsx
  src/app/[locale]/estimateRequest/create/page.tsx
  src/app/[locale]/favoriteMover/page.tsx
  src/app/[locale]/layout.tsx
  src/app/[locale]/moverMyPage/edit/page.tsx
  src/app/[locale]/moverMyPage/page.tsx
  src/app/[locale]/not-found.tsx
  src/app/[locale]/notification/page.tsx
  src/app/[locale]/page.tsx
  src/app/[locale]/profile/edit/page.tsx
  src/app/[locale]/profile/register/page.tsx
  src/app/[locale]/providers.tsx
  src/app/[locale]/review/layout.tsx
  src/app/[locale]/review/writable/page.tsx
  src/app/[locale]/review/written/page.tsx
  src/app/[locale]/searchMover/[id]/page.tsx
  src/app/[locale]/searchMover/page.tsx
  src/app/page.tsx
  src/components/common/LanguageSwitcher.tsx
  src/components/common/chips/MoveTypeLabel.tsx
  src/i18n/navigation.ts
  src/i18n/request.ts
  src/i18n/routing.ts
  src/messages/en.json
  src/messages/ko.json
  src/messages/zh.json
  src/middleware.ts
  src/pageComponents/auth/userSignin/UserSigninPage.tsx
  src/pageComponents/landing/LadingPage.tsx
  src/pageComponents/moverMyPage/edit/EditPage.tsx
  src/pageComponents/searchMover/SearchMoverDetailPage.tsx
  src/pageComponents/searchMover/SearchMoverPage.tsx
Labels: 승준, feat, fix, refactor, priority: critical

#181 fix : i18n 적용에 맞춰 미들웨어 설정 수정
  src/components/common/chips/MoveTypeLabel.tsx
  src/components/common/gnb/LogoAndTab.tsx
  src/components/estimate/LabelArea.tsx
  src/components/estimateRequest/(my)/CardList.tsx
  src/middleware.ts
  src/pageComponents/estimate/received/MoverReceivedPage.tsx
  src/pageComponents/profile/edit/CustomerEditPage.tsx
  src/utils/locale.ts
Labels: 민규, fix, priority: critical

#182 Feat: 기사님 프로필 수정 api 연동 / 기사님 프로필 수정 및 기본정보 수정 페이지의 경로를 locale 기반으로 수정
  src/app/[locale]/moverMyPage/page.tsx
  src/constant/devNavRouteGroups.ts
  src/lib/api/user.api.ts
  src/pageComponents/moverMyPage/MoverMyPageComponent.tsx
  src/pageComponents/moverMyPage/edit/EditPage.tsx
  src/pageComponents/moverMyPage/page.tsx
  src/pageComponents/profile/edit/MoverEditPage.tsx
  src/types/user.ts
Labels: 세준, feat, priority: medium

#185 [#184] feat&fix : 견적 모든 페이지 수정 및 리펙토링
  src/components/estimate/(my)/rejected/[id]/RejectDetailMain.tsx
  src/components/estimate/(my)/request/[id]/RequestDetailMain.tsx
  src/components/estimate/CardList.tsx
  src/components/estimate/LabelArea.tsx
  src/components/estimateRequest/(my)/DetailPageMainSeaction.tsx
  src/components/estimateRequest/(my)/MoverInfo.tsx
  src/components/estimateRequest/(my)/received/EstimateRequestInfo.tsx
  src/lib/api/customerEstimateRequest.ts
  src/lib/api/moverEstimate.api.ts
  src/pageComponents/estimate/(my)/rejected/RejectedPage.tsx
  src/pageComponents/estimate/(my)/request/RequsetPage.tsx
  src/pageComponents/estimate/received/MoverReceivedPage.tsx
  src/pageComponents/estimateRequest/(my)/pending/UserPendingEstimateRequestPage.tsx
  src/types/moverEstimate.ts
  src/utils/regionMapping.ts
Labels: 수빈, fix, refactor

#187 [#58] feat : 구글/카카오/네이버 소셜 로그인 구현
  src/app/[locale]/(auth)/callback/page.tsx
  src/lib/api/auth.api.ts
  src/middleware.ts
  src/pageComponents/auth/callback/AuthCallback.tsx
  src/pageComponents/auth/moverSignin/MoverSigninPage.tsx
  src/pageComponents/auth/moverSignup/MoverSignupPage.tsx
  src/pageComponents/auth/userSignin/UserSigninPage.tsx
  src/pageComponents/auth/userSignup/UserSignupPage.tsx
  src/providers/AuthProvider.tsx
Labels: 민규, feat

#190 [#40] feat:견적 찜하기 연동 및 견적서 제한 모달구현
  src/components/common/button/Favorite.tsx
  src/components/estimate/CardList.tsx
  src/components/estimateRequest/(my)/CardList.tsx
  src/components/estimateRequest/(my)/MoverInfo.tsx
  src/lib/api/customerEstimateRequest.api.ts
  src/lib/api/moverEstimate.api.ts
  src/pageComponents/estimate/(my)/rejected/RejectedPage.tsx
  src/pageComponents/estimate/(my)/request/RequsetPage.tsx
  src/pageComponents/estimate/received/MoverReceivedPage.tsx
  src/pageComponents/estimateRequest/(my)/pending/UserPendingEstimateRequestPage.tsx
  src/pageComponents/estimateRequest/(my)/pending/[id]/UserPendingEstimateRequestDetailPage.tsx
  src/pageComponents/estimateRequest/(my)/received/UserReceivedEstimateRequestPage.tsx
  src/pageComponents/estimateRequest/(my)/received/[id]/UserReceivedEstimateRequestDetailPage.tsx
  src/services/favoriteService.ts
Labels: 수빈, feat, fix

#194 [#193] Refactor/review 타입 및 기타 코드 수정.
  src/components/review/writable/ReviewWriteModal.tsx
  src/components/review/writable/StarRating.tsx
  src/components/review/writable/WritableMoverCard.tsx
  src/components/review/written/WrittenMoverCard.tsx
  src/lib/api/review.api.ts
  src/pageComponents/review/writable/WritableReviewPage.tsx
  src/types/review.ts
Labels: 재욱, refactor, priority: medium

#195 [#188] feat : [로그인/회원가입, 프로필 수정] 번역 작업
  src/components/common/gnb/GnbActions.tsx
  src/hooks/useValidationRules.ts
  src/lib/api/auth.api.ts
  src/messages/en.json
  src/messages/ko.json
  src/messages/zh.json
  src/middleware.ts
  src/pageComponents/auth/callback/AuthCallback.tsx
  src/pageComponents/auth/moverSignin/MoverSigninPage.tsx
  src/pageComponents/auth/moverSignup/MoverSignupPage.tsx
  src/pageComponents/auth/userSignin/UserSigninPage.tsx
  src/pageComponents/auth/userSignup/UserSignupPage.tsx
  src/pageComponents/profile/edit/CustomerEditPage.tsx
  src/pageComponents/profile/register/CustomerRegisterPage.tsx
  src/pageComponents/profile/register/MoverRegisterPage.tsx
  src/utils/validators.ts
Labels: 민규, feat

#200 [#196] feat: 견적 모든 페이지 다국어 기능 적용
  src/components/common/tab/EstimateRequestAndEstimateTab.tsx
  src/components/estimate/(my)/rejected/[id]/RejectDetailMain.tsx
  src/components/estimate/(my)/request/[id]/RequestDetailMain.tsx
  src/components/estimate/CardList.tsx
  src/components/estimate/LabelArea.tsx
  src/components/estimate/received/Dropdown.tsx
  src/components/estimate/received/FilterAndSearchSection.tsx
  src/components/estimate/received/ModalChild.tsx
  src/components/estimate/received/PcFillterSection.tsx
  src/components/estimate/received/SelectCheckBox.tsx
  src/components/estimate/received/SelectMovingType.tsx
  src/components/estimate/received/SmallFilterSection.tsx
  src/components/estimateRequest/(my)/CardList.tsx
  src/components/estimateRequest/(my)/DetailMoveInfo.tsx
  src/components/estimateRequest/(my)/DetailPageMainSeaction.tsx
  src/components/estimateRequest/(my)/LabelAndTitleSection.tsx
  src/components/estimateRequest/(my)/LgButtonSection.tsx
  src/components/estimateRequest/(my)/MoverInfo.tsx
  src/components/estimateRequest/(my)/ShareSection.tsx
  src/components/estimateRequest/(my)/pending/RequestEstimateRequest.tsx
  src/components/estimateRequest/(my)/received/EstimateListSection.tsx
  src/components/estimateRequest/(my)/received/EstimateRequestInfo.tsx
  src/components/estimateRequest/(my)/received/LastButtonSection.tsx
  src/messages/en.json
  src/messages/ko.json
  src/messages/zh.json
  src/pageComponents/estimate/(my)/rejected/RejectedPage.tsx
  src/pageComponents/estimate/(my)/rejected/[id]/RejectedDetailPage.tsx
  src/pageComponents/estimate/(my)/request/RequsetPage.tsx
  src/pageComponents/estimate/(my)/request/[id]/RequsetDetailPage.tsx
  src/pageComponents/estimate/received/MoverReceivedPage.tsx
  src/pageComponents/estimateRequest/(my)/pending/UserPendingEstimateRequestPage.tsx
  src/pageComponents/estimateRequest/(my)/pending/[id]/UserPendingEstimateRequestDetailPage.tsx
  src/pageComponents/estimateRequest/(my)/received/UserReceivedEstimateRequestPage.tsx
  src/pageComponents/estimateRequest/(my)/received/[id]/UserReceivedEstimateRequestDetailPage.tsx
  src/types/moverEstimate.ts
  src/utils/dateUtils.ts
Labels: 수빈, feat, fix

#201 [견적] fix:버셀배포 오류수정
  src/i18n/request.ts
  src/messages/en.json
  src/messages/ko.json
  src/messages/zh.json
  src/pageComponents/moverMyPage/edit/EditPage.tsx
Labels: 수빈, fix, test

#210 [#209] feat: 기사님 찾기 및 기사님 상세 다국어 기능 적용
  package-lock.json
  src/app/[locale]/searchMover/[id]/page.tsx
  src/components/common/button/Button.tsx
  src/components/common/dropdown/CustomDropdown.tsx
  src/components/common/dropdown/SortDropdown.tsx
  src/components/searchMover/%5Bid%5D/ReviewList.tsx
  src/components/searchMover/FavoriteMoverList.tsx
  src/components/searchMover/FilterBar.tsx
  src/components/searchMover/MoverList.tsx
  src/components/searchMover/SearchBar.tsx
  src/components/searchMover/SortBar.tsx
  src/components/searchMover/[id]/Chip.tsx
  src/components/searchMover/[id]/DetailInformation.tsx
  src/components/searchMover/[id]/MoverIntro.tsx
  src/components/searchMover/[id]/RequestButton.tsx
  src/components/searchMover/[id]/ReviewAvg.tsx
  src/components/searchMover/[id]/ReviewList.tsx
  src/components/searchMover/[id]/TopBar.tsx
  src/hooks/useLikeToggle.ts
  src/lib/api/findMover.api.ts
  src/lib/utils/mockReviewData.ts
  src/lib/utils/translationUtils.ts
  src/messages/en.json
  src/messages/ko.json
  src/messages/zh.json
  src/pageComponents/favoriteMover/page.tsx
  src/pageComponents/landing/LadingPage.tsx
  src/pageComponents/searchMover/SearchMoverDetailPage.tsx
  src/pageComponents/searchMover/SearchMoverPage.tsx
  src/stores/searchMoverStore.ts
  src/types/api.types.ts
  src/types/button.ts
  src/types/component.types.ts
  src/types/findMover.ts
  src/types/mover.types.ts
  src/types/moverDetail.ts
  src/types/review.ts
Labels: 지연, feat, fix

#204 [#172] [#197] [#199] Feat/notification 실시간 알림 기능 문제 해결.
  src/components/common/dropdown/UserActionDropdown.tsx
  src/components/common/gnb/GnbActions.tsx
  src/components/notification/NotificationList.tsx
  src/providers/NotificationSSEProvider.tsx
  src/stores/notificationStore.ts
  src/types/notification.types.ts
Labels: 재욱, fix, refactor, priority: medium

#211 fix : auth, profile 버그 수정
  src/pageComponents/auth/moverSignin/MoverSigninPage.tsx
  src/pageComponents/auth/moverSignup/MoverSignupPage.tsx
  src/pageComponents/auth/userSignin/UserSigninPage.tsx
  src/pageComponents/auth/userSignup/UserSignupPage.tsx
  src/pageComponents/profile/register/MoverRegisterPage.tsx
Labels: 민규, fix

#215 fix:기사님 마이페이지 리뷰 리스트 적용 및 코드 최적화
  src/components/searchMover/[id]/ReviewList.tsx
  src/pageComponents/moverMyPage/MoverMyPage.tsx
Labels: 세준, fix, priority: medium

#214 기사님 찾기 및 기사님 상세 페이지 리팩토링
  src/assets/img/landing/move-type.png
  src/assets/img/landing/truck.png
  src/assets/img/landing/type-lg.png
  src/assets/img/landing/type-md.svg
  src/assets/img/landing/type-sm.png
  src/components/searchMover/FavoriteMoverList.tsx
  src/components/searchMover/FilterBar.tsx
  src/components/searchMover/MoverCard.tsx
  src/components/searchMover/MoverList.tsx
  src/components/searchMover/[id]/MoverIntro.tsx
  src/components/searchMover/[id]/RequestButton.tsx
  src/hooks/useLikeToggle.ts
  src/hooks/useMoverData.ts
  src/middleware.ts
  src/pageComponents/landing/LadingPage.tsx
  src/pageComponents/searchMover/SearchMoverDetailPage.tsx
  src/pageComponents/searchMover/SearchMoverPage.tsx
Labels: 지연, fix, chore, refactor

#216 Feat:기사님 페이지 다국어 기능 완성 및 UI 개선
  src/messages/en.json
  src/messages/ko.json
  src/messages/zh.json
  src/pageComponents/moverMyPage/MoverMyPage.tsx
  src/pageComponents/moverMyPage/edit/EditPage.tsx
  src/pageComponents/profile/edit/MoverEditPage.tsx
Labels: 세준, feat, priority: medium

#222 fix : 기사님 프로필 등록 오류 수정
  src/pageComponents/profile/register/CustomerRegisterPage.tsx
  src/pageComponents/profile/register/MoverRegisterPage.tsx
Labels: 민규, fix

#225 [#224] Feat/gnb GNB 및 유저 드롭다운 다국어 작업.
  src/components/common/dropdown/UserActionDropdown.tsx
  src/components/common/gnb/GnbActions.tsx
Labels: 재욱, fix, priority: high

#228 [#218]fix: 다크 모드에서 css가 잘못 출력되는 문제 해결
  src/app/globals.css
Labels: 승준, fix, priority: critical

#229 feat:기본정보 수정 모달 구현
  src/messages/en.json
  src/messages/ko.json
  src/messages/zh.json
  src/pageComponents/moverMyPage/edit/EditPage.tsx
Labels: 세준, feat, priority: low

#232 [#227]feat: 기사님 일정관리 페이지 api 연결
  src/components/common/gnb/GnbActions.tsx
  src/components/moverMyPage/schedule/CalendarWithSchedule.tsx
  src/hooks/useMoverScheduleApi.tsx
  src/lib/api/moverScheduleService.ts
  src/messages/en.json
  src/messages/ko.json
  src/messages/zh.json
  src/pageComponents/moverMyPage/schedule/MoverSchedulePage.tsx
  src/types/schedule.ts
  src/utils/scheduleUtils.ts
Labels: 승준, fix, ready for review

#235 [#234] refactor:견적 요청 중복 코드 삭제 및 로딩 구현
  src/app/globals.css
  src/components/common/pending/MovingTruckLoader.tsx
  src/components/estimateRequest/EstimateRequestPageWrapper.tsx
  src/components/estimateRequest/common/EstimateRequestFlow.tsx
  src/components/estimateRequest/common/EstimateRequestLayout.tsx
  src/components/estimateRequest/common/EstimateRequestStepRenderer.tsx
  src/components/estimateRequest/create/ProgressBar.tsx
  src/components/estimateRequest/create/SpeechBubble.tsx
  src/hooks/useEstimateRequestApi.tsx
  src/pageComponents/estimateRequest/create/EstimateRequestCreatePage.tsx
  src/pageComponents/estimateRequest/edit/EstimateRequestEditPage.tsx
Labels: 승준, refactor, ready for review

#233 [#231] refactor : 라이트하우스 기반 로그인/회원가입 최적화
  src/app/[locale]/(auth)/callback/page.tsx
  src/components/auth/.gitkeep
  src/components/auth/MascotCharacter.tsx
  src/components/auth/SocialLoginButtons.tsx
  src/components/auth/index.ts
  src/components/auth/signin/.gitkeep
  src/components/auth/signin/SigninForm.tsx
  src/components/auth/signin/SigninHeader.tsx
  src/components/auth/signin/index.ts
  src/components/auth/signup/.gitkeep
  src/components/auth/signup/SignupForm.tsx
  src/components/auth/signup/SignupHeader.tsx
  src/components/auth/signup/index.ts
  src/components/common/gnb/Gnb.tsx
  src/messages/en.json
  src/messages/ko.json
  src/messages/zh.json
  src/pageComponents/auth/callback/AuthCallback.tsx
  src/pageComponents/auth/moverSignin/MoverSigninPage.tsx
  src/pageComponents/auth/moverSignup/MoverSignupPage.tsx
  src/pageComponents/auth/userSignin/UserSigninPage.tsx
  src/pageComponents/auth/userSignup/UserSignupPage.tsx
  src/types/user.ts
Labels: 민규, refactor

#243 [#236] 프로필 등록/수정 리팩터링
  package-lock.json
  package.json
  src/assets/img/etc/profile-upload-skeleton.webp
  src/components/common/gnb/Gnb.tsx
  src/components/common/gnb/GnbActions.tsx
  src/components/profile/.gitkeep
  src/components/profile/edit/.gitkeep
  src/components/profile/edit/ProfileEditActionButtons.tsx
  src/components/profile/edit/ProfileEditFormField.tsx
  src/components/profile/edit/ProfileEditHeader.tsx
  src/components/profile/edit/ProfileEditImageUpload.tsx
  src/components/profile/edit/ProfileEditRegionSelection.tsx
  src/components/profile/edit/ProfileEditServiceSelection.tsx
  src/components/profile/edit/index.ts
  src/components/profile/register/.gitkeep
  src/components/profile/register/FormField.tsx
  src/components/profile/register/ProfileFormButton.tsx
  src/components/profile/register/ProfileFormHeader.tsx
  src/components/profile/register/ProfileImageUpload.tsx
  src/components/profile/register/RegionSelection.tsx
  src/components/profile/register/ServiceSelection.tsx
  src/components/profile/register/index.ts
  src/lib/api/auth.api.ts
  src/lib/api/fetcher.api.ts
  src/messages/en.json
  src/messages/ko.json
  src/messages/zh.json
  src/pageComponents/profile/edit/CustomerEditPage.tsx
  src/pageComponents/profile/register/CustomerRegisterPage.tsx
  src/pageComponents/profile/register/MoverRegisterPage.tsx
  src/providers/AuthProvider.tsx
  src/utils/validators.ts
Labels: 민규, refactor

#245 feat: 기사님 마이페이지에 동적 데이터 번역 기능 추가
  src/lib/api/user.api.ts
  src/pageComponents/moverMyPage/MoverMyPage.tsx
Labels: 세준, feat, priority: low
