Repository WooGie911/Moving_FE, pull requests merged in 2025-08, with the labels that each got.

#246 fix : 토큰 리프레쉬 에러 수정
  src/lib/api/fetcher.api.ts
Labels: fix

#252 [#234][#241]repactor:견적 요청과 기사 일정관리 프론트 리팩토링
  src/app/[locale]/not-found.tsx
  src/app/layout.tsx
  src/app/not-found.tsx
  src/assets/icon/checkbox/icon-checkbox-circle-active.png
  src/assets/icon/checkbox/roundCheck.svg
  src/assets/img/etc/homeMoving.webp
  src/assets/img/etc/homemove.png
  src/assets/img/etc/officeMoving.webp
  src/assets/img/etc/officemove.png
  src/assets/img/etc/smallMoving.webp
  src/assets/img/etc/smallmove.png
  src/components/common/gnb/GnbActions.tsx
  src/components/common/input/Checkbox.tsx
  src/components/estimateRequest/EstimateRequestPageWrapper.tsx
  src/components/estimateRequest/common/EstimateRequestFlow.tsx
  src/components/estimateRequest/common/EstimateRequestLayout.tsx
  src/components/estimateRequest/create/SpeechBubble.tsx
  src/components/estimateRequest/create/card/AddressCard.tsx
  src/components/estimateRequest/create/card/MovingTypeCard.tsx
  src/components/estimateRequest/create/sections/MovingTypeSection.tsx
  src/components/moverMyPage/schedule/CalendarWithSchedule.tsx
  src/constant/gnbItems.ts
  src/constant/schedule.ts
  src/hooks/useEstimateRequestForm.tsx
  src/hooks/useMoverScheduleApi.tsx
  src/lib/api/estimateRequest.api.ts
  src/lib/api/moverScheduleService.ts
  src/messages/en.json
  src/messages/ko.json
  src/messages/zh.json
  src/pageComponents/estimateRequest/create/EstimateRequestCreatePage.tsx
  src/pageComponents/estimateRequest/edit/EstimateRequestEditPage.tsx
  src/pageComponents/moverMyPage/schedule/MoverSchedulePage.tsx
  src/types/estimateRequest.ts
  src/types/schedule.ts
  src/utils/apiUtils.ts
  src/utils/scheduleUtils.ts
Labels: 승준, fix, refactor, priority: critical, ready for review

#254 [#247] feat : 간편 로그인 전환 기능 구현 및 사이드바 오류 수정
  package-lock.json
  package.json
  src/app/layout.tsx
  src/components/common/gnb/Gnb.tsx
  src/components/common/gnb/GnbActions.tsx
  src/components/common/gnb/ProfileModal.tsx
  src/components/common/gnb/RoleToggle.tsx
  src/components/common/gnb/SideGnb.tsx
  src/hooks/useSwitchUserType.tsx
  src/lib/api/auth.api.ts
  src/messages/en.json
  src/messages/ko.json
  src/messages/zh.json
  src/middleware.ts
  src/pageComponents/profile/edit/CustomerEditPage.tsx
  src/providers/AuthProvider.tsx
Labels: 민규, feat, refactor

#259 fix : 소셜 로그인 간편 전환 수정
  src/components/common/gnb/RoleToggle.tsx
  src/lib/api/auth.api.ts
Labels: 민규, fix

#261 [#247] refactor : 프로필 모달 호버 애니메이션 추가 및 간편 전환 호버 메시지창 개선 및 소셜 로그인 계정으로 로컬 로그인시 에러 반환 모달 출력
  src/components/common/gnb/ProfileModal.tsx
  src/components/common/gnb/RoleToggle.tsx
  src/messages/en.json
  src/messages/ko.json
  src/messages/zh.json
  src/pageComponents/profile/register/CustomerRegisterPage.tsx
  src/pageComponents/profile/register/MoverRegisterPage.tsx
Labels: 민규, refactor

#262 repactor: 견적 요청 리팩토링
  src/hooks/useEstimateRequestAddressModal.tsx
  src/hooks/useEstimateRequestApi.tsx
  src/messages/en.json
  src/messages/ko.json
  src/messages/zh.json
Labels: 승준, refactor, priority: low, ready for review

#268 fix : 로그인 오류 수정
  src/providers/AuthProvider.tsx
Labels: 민규, fix

#267 [#265] - 견적 : 플로우테스트 수정 및 유저기능 추가
  src/assets/icon/menu/icon-delete.png
  src/components/common/input/PasswordInput.tsx
  src/components/common/input/SearchInput.tsx
  src/components/common/tab/EstimateRequestAndEstimateTab.tsx
  src/components/common/tab/Tab.tsx
  src/components/estimate/(my)/rejected/[id]/RejectDetailMain.tsx
  src/components/estimate/(my)/request/[id]/RequestDetailMain.tsx
  src/components/estimate/CardList.tsx
  src/components/estimate/LabelArea.tsx
  src/components/estimate/received/FilterAndSearchSection.tsx
  src/components/estimate/received/ModalChild.tsx
  src/components/estimateRequest/(my)/CardList.tsx
  src/components/estimateRequest/(my)/DetailMoveInfo.tsx
  src/components/estimateRequest/(my)/DetailPageMainSeaction.tsx
  src/components/estimateRequest/(my)/LabelAndTitleSection.tsx
  src/components/estimateRequest/(my)/LgButtonSection.tsx
  src/components/estimateRequest/(my)/MoverInfo.tsx
  src/components/estimateRequest/(my)/pending/CompleteModal.tsx
  src/components/estimateRequest/(my)/pending/RequestEstimateRequest.tsx
  src/components/estimateRequest/(my)/received/EstimateListSection.tsx
  src/components/estimateRequest/(my)/received/EstimateRequestAndEstimates.tsx
  src/components/estimateRequest/(my)/received/EstimateRequestInfo.tsx
  src/components/estimateRequest/(my)/received/LastButtonSection.tsx
  src/hooks/useEstimateRequestAddressModal.tsx
  src/hooks/useEstimateRequestForm.tsx
  src/hooks/useLikeToggle.ts
  src/lib/api/customerEstimateRequest.api.ts
  src/lib/api/moverEstimate.api.ts
  src/lib/utils/dateFormatUtils.ts
  src/lib/utils/formatDateWithDay.ts
  src/lib/utils/formatNumber.ts
  src/lib/utils/formatRequestDate.ts
  src/lib/utils/getMovingTypeTranslated.ts
  src/lib/utils/mapServiceTypeToMoveType.ts
  src/messages/en.json
  src/messages/ko.json
  src/messages/zh.json
  src/pageComponents/estimate/(my)/rejected/RejectedPage.tsx
  src/pageComponents/estimate/(my)/rejected/[id]/RejectedDetailPage.tsx
  src/pageComponents/estimate/(my)/request/RequsetPage.tsx
  src/pageComponents/estimate/(my)/request/[id]/RequsetDetailPage.tsx
  src/pageComponents/estimate/received/MoverReceivedPage.tsx
  src/pageComponents/estimateRequest/(my)/pending/UserPendingEstimateRequestPage.tsx
  src/pageComponents/estimateRequest/(my)/pending/[id]/UserPendingEstimateRequestDetailPage.tsx
  src/pageComponents/estimateRequest/(my)/received/UserReceivedEstimateRequestPage.tsx
  src/pageComponents/estimateRequest/(my)/received/[id]/UserReceivedEstimateRequestDetailPage.tsx
  src/types/customerEstimateRequest.ts
  src/types/estimateRequest.ts
  src/types/mover.types.ts
  src/types/moverEstimate.ts
  src/types/review.ts
Labels: 수빈, feat, fix, refactor

#270 [#269] feat : 배포 상태에따라 내부 에러 메시지 숨기기가 가능한 유틸함수 구현
  src/lib/api/user.api.ts
  src/providers/AuthProvider.tsx
  src/utils/auth.ts
  src/utils/logDevError.ts
Labels: 민규, feat

#273 Feat: 소셜 로그인 유저 기본정보 수정 페이지 최적화 및 프로필 글자 제한 추가
  src/components/common/button/Favorite.tsx
  src/components/common/input/TextAreaInput.tsx
  src/components/common/input/TextInput.tsx
  src/pageComponents/moverMyPage/MoverMyPage.tsx
  src/pageComponents/moverMyPage/edit/EditPage.tsx
  src/pageComponents/profile/edit/MoverEditPage.tsx
Labels: 세준, fix, priority: medium

#274 [#265] 견적페이지- 좋아요 기능 기능개선
  src/components/common/button/Favorite.tsx
  src/components/estimate/CardList.tsx
  src/components/estimateRequest/(my)/CardList.tsx
  src/components/estimateRequest/(my)/LgButtonSection.tsx
  src/components/estimateRequest/(my)/MoverInfo.tsx
  src/components/estimateRequest/(my)/received/EstimateListSection.tsx
  src/components/estimateRequest/(my)/received/LastButtonSection.tsx
  src/lib/api/customerEstimateRequest.api.ts
  src/lib/api/estimateRequest.server.ts
  src/pageComponents/estimate/(my)/rejected/[id]/RejectedDetailPage.tsx
  src/pageComponents/estimate/(my)/request/RequsetPage.tsx
  src/pageComponents/estimate/(my)/request/[id]/RequsetDetailPage.tsx
  src/pageComponents/estimate/received/MoverReceivedPage.tsx
  src/pageComponents/estimateRequest/(my)/pending/UserPendingEstimateRequestPage.tsx
  src/pageComponents/estimateRequest/(my)/received/UserReceivedEstimateRequestPage.tsx
  src/pageComponents/estimateRequest/(my)/received/[id]/UserReceivedEstimateRequestDetailPage.tsx
Labels: 수빈, fix, refactor

#277 [#269] feat : 프로필 등록/수정 seo 적용
  src/app/[locale]/profile/edit/page.tsx
  src/app/[locale]/profile/register/page.tsx
  src/components/common/gnb/RoleToggle.tsx
  src/messages/en.json
  src/messages/ko.json
  src/messages/zh.json
  src/pageComponents/profile/edit/IndexEditPage.tsx
  src/pageComponents/profile/register/IndexRegisterPage.tsx
Labels: 민규, feat

#278 bug: 타입정의 오류 해결
  src/components/searchMover/[id]/Chip.tsx
  src/components/searchMover/[id]/DetailInformation.tsx
  src/components/searchMover/[id]/MoverIntro.tsx
  src/components/searchMover/[id]/RequestButton.tsx
  src/components/searchMover/[id]/ReviewList.tsx
  src/types/mover.types.ts
Labels: 지연, priority: critical, bug

#281 fix:견적요청 일정관리 페이지 수정
  src/app/[locale]/moverMyPage/schedule/page.tsx
  src/components/estimateRequest/common/EstimateRequestLayout.tsx
  src/components/estimateRequest/create/Calendar.tsx
  src/constant/estimateRequestStyles.ts
  src/messages/en.json
  src/messages/ko.json
  src/messages/zh.json
  src/pageComponents/moverMyPage/schedule/MoverSchedulePage.tsx
Labels: 승준, fix, refactor, ready for review

#287 refactor: 기사님 상세 리뷰 동적 번역 적용
  src/components/searchMover/[id]/ReviewList.tsx
  src/lib/api/findMover.api.ts
Labels: 지연, refactor

#289 fix:토스트 라이브러리를 사용하여 토스트 디자인 변경
  src/app/[locale]/layout.tsx
  src/app/globals.css
  src/hooks/useEstimateRequestApi.tsx
  src/hooks/useSwitchUserType.tsx
  src/pageComponents/favoriteMover/FavoriteMoverPage.tsx
  src/utils/shareUtils.ts
  src/utils/toastUtils.ts
Labels: 승준, fix, ready for review

#286 [#263] [#285] [리뷰] FE 성능 최적화 및 동적데이터 다국어 기능 구현.
  .gitignore
  next.config.ts
  package-lock.json
  package.json
  sentry.edge.config.ts
  sentry.server.config.ts
  src/app/[locale]/review/writable/page.tsx
  src/app/[locale]/review/written/page.tsx
  src/app/global-error.tsx
  src/assets/icon/arrow/icon-arrow.webp
  src/assets/icon/etc/icon-estimate.png
  src/assets/icon/etc/icon-estimate.webp
  src/assets/icon/star/icon-star-active-lg.webp
  src/assets/icon/star/icon-star-active-sm.webp
  src/assets/icon/star/icon-star-inactive-lg.webp
  src/assets/icon/star/icon-star-inactive-sm.webp
  src/assets/img/mascot/moverprofile-lg.webp
  src/assets/img/mascot/notfound.webp
  src/components/review/writable/ReviewWriteModal.tsx
  src/components/review/writable/StarRating.tsx
  src/components/review/writable/WritableMoverCard.tsx
  src/components/review/writable/WritableMoverCardList.tsx
  src/components/review/written/WrittenMoverCard.tsx
  src/instrumentation-client.ts
  src/instrumentation.ts
  src/lib/api/review.api.ts
  src/messages/en.json
  src/messages/ko.json
  src/messages/zh.json
  src/pageComponents/review/writable/WritableReviewPage.tsx
  src/pageComponents/review/written/WrittenReviewPage.tsx
  src/types/review.ts
Labels: 재욱, feat, refactor, priority: medium

#290 fix : 다이렉트 오류 및 에러 모달 숨김 적용
  src/app/[locale]/(auth)/loading.tsx
  src/app/[locale]/profile/loading.tsx
  src/components/auth/signin/SigninForm.tsx
  src/components/auth/signup/SignupForm.tsx
  src/lib/api/auth.api.ts
  src/pageComponents/profile/edit/IndexEditPage.tsx
  src/pageComponents/profile/register/CustomerRegisterPage.tsx
  src/pageComponents/profile/register/IndexRegisterPage.tsx
  src/pageComponents/profile/register/MoverRegisterPage.tsx
  src/providers/AuthProvider.tsx
  src/providers/QueryProvider.tsx
  src/utils/auth.ts
Labels: 민규, fix

#291 [#269] refactor : 프로필 수정/등록 로딩 페이지 적용
  src/messages/en.json
  src/messages/ko.json
  src/messages/zh.json
  src/pageComponents/profile/edit/IndexEditPage.tsx
  src/pageComponents/profile/register/IndexRegisterPage.tsx
Labels: 민규, fix

#295 refactor: 랜딩페이지 ssr로 변경
  src/app/globals.css
  src/pageComponents/landing/LadingPage.tsx
Labels: 지연, refactor

#299 fix : 시나리오테스트 견적 - 유저 및 기사 오류수정
  src/app/[locale]/estimate/(my)/rejected/[id]/page.tsx
  src/app/[locale]/estimate/(my)/rejected/page.tsx
  src/app/[locale]/estimate/(my)/request/[id]/page.tsx
  src/app/[locale]/estimate/(my)/request/page.tsx
  src/components/common/chips/MoveTypeLabel.tsx
  src/components/common/input/Checkbox.tsx
  src/components/estimate/(my)/rejected/[id]/RejectDetailMain.tsx
  src/components/estimate/(my)/request/[id]/RequestDetailMain.tsx
  src/components/estimate/CardList.tsx
  src/components/estimate/received/ModalChild.tsx
  src/components/estimateRequest/(my)/CardList.tsx
  src/components/estimateRequest/(my)/DetailMoveInfo.tsx
  src/components/estimateRequest/(my)/DetailPageMainSeaction.tsx
  src/components/estimateRequest/(my)/LabelAndTitleSection.tsx
  src/components/estimateRequest/(my)/MoverInfo.tsx
  src/components/estimateRequest/(my)/received/EstimateListSection.tsx
  src/components/estimateRequest/(my)/received/EstimateRequestAndEstimates.tsx
  src/components/estimateRequest/(my)/received/EstimateRequestInfo.tsx
  src/lib/utils/mapServiceTypeToMoveType.ts
  src/messages/en.json
  src/messages/ko.json
  src/messages/zh.json
  src/pageComponents/estimate/(my)/rejected/MoverRejectedPage.tsx
  src/pageComponents/estimate/(my)/rejected/[id]/MoverRejectedDetailPage.tsx
  src/pageComponents/estimate/(my)/request/MoverRequestPage.tsx
  src/pageComponents/estimate/(my)/request/[id]/MoverRequestDetailPage.tsx
  src/pageComponents/estimate/received/MoverReceivedPage.tsx
  src/types/customerEstimateRequest.ts
Labels: 수빈, fix, refactor, bug

#300 fix : 프로필 등록시 쿠키 최신화가 안되던 문제 수정
  src/lib/api/auth.api.ts
  src/lib/api/fetcher.api.ts
  src/lib/api/user.api.ts
  src/providers/AuthProvider.tsx
Labels: 민규, fix

#303 [#301] [#302] [알림] 데이터 리패칭 문제 해결 및 FE 다국어 처리.
  src/components/common/gnb/GnbActions.tsx
  src/components/notification/NotificationList.tsx
  src/lib/api/notification.api.ts
  src/messages/en.json
  src/messages/ko.json
  src/messages/zh.json
  src/providers/NotificationSSEProvider.tsx
  src/stores/notificationStore.ts
Labels: 재욱, feat, priority: critical, bug

#305 Bug/mover
  src/components/common/chips/MoveTypeLabel.tsx
  src/components/searchMover/FavoriteMoverList.tsx
  src/messages/en.json
Labels: 지연, bug

#310 [#307] refactor : 번역 스위치 개선 및 기사님 찾기 hover css 개선
  src/components/common/LanguageSwitcher.tsx
  src/components/common/dropdown/CustomDropdown.tsx
  src/components/common/dropdown/SortDropdown.tsx
  src/components/common/gnb/ProfileModal.tsx
  src/components/searchMover/FilterBar.tsx
  src/providers/AuthProvider.tsx
Labels: 민규, refactor

#311 [#309] [알림] 일반 유저와 기사님 알림 따로 처리.
  src/components/common/gnb/GnbActions.tsx
  src/components/notification/NotificationList.tsx
  src/lib/api/notification.api.ts
  src/stores/notificationStore.ts
Labels: 재욱, feat, priority: medium

#315 feat: 인증 완료 후에만 견적 요청 API 호출하도록 조건 추가
  src/app/[locale]/profile/loading.tsx
  src/middleware.ts
  src/pageComponents/estimate/received/MoverReceivedPage.tsx
Labels: 민규, feat

#316 Fix/favorite
  src/app/[locale]/layout.tsx
  src/components/common/LanguageInitializer.tsx
  src/components/common/LanguageSwitcher.tsx
  src/middleware.ts
  src/pageComponents/favoriteMover/FavoriteMoverPage.tsx
  src/pageComponents/searchMover/SearchMoverPage.tsx
  src/utils/languageUtils.ts
Labels: 승준, ready for review

#321 [#255] fix: 시나리오테스트 피드백 및 수정사항 개선
  src/components/estimate/CardList.tsx
  src/components/estimate/received/ModalChild.tsx
  src/components/estimateRequest/(my)/DetailPageMainSeaction.tsx
  src/components/estimateRequest/(my)/LabelAndTitleSection.tsx
  src/components/estimateRequest/(my)/MoverInfo.tsx
  src/messages/en.json
  src/messages/ko.json
  src/messages/zh.json
  src/pageComponents/estimate/(my)/rejected/MoverRejectedPage.tsx
  src/pageComponents/estimate/(my)/rejected/[id]/MoverRejectedDetailPage.tsx
  src/pageComponents/estimate/(my)/request/MoverRequestPage.tsx
  src/pageComponents/estimate/(my)/request/[id]/MoverRequestDetailPage.tsx
  src/pageComponents/estimate/received/MoverReceivedPage.tsx
  src/pageComponents/estimateRequest/(my)/pending/UserPendingEstimateRequestPage.tsx
  src/pageComponents/estimateRequest/(my)/pending/[id]/UserPendingEstimateRequestDetailPage.tsx
  src/pageComponents/estimateRequest/(my)/received/UserReceivedEstimateRequestPage.tsx
  src/pageComponents/estimateRequest/(my)/received/[id]/UserReceivedEstimateRequestDetailPage.tsx
  src/utils/dateUtils.ts
Labels: 수빈, feat, fix

#322 fix : 미들웨어 리다이렉트 문제 수정 및 토큰 재발급 로직 강화
  src/middleware.ts
  src/providers/AuthProvider.tsx
  src/utils/decodeAccessToken.ts
Labels: 민규, fix

#329 [#318] [#320] [#327] [알림] 3차 QA 피드백 반영 및 sentry 모니터링, CSRF 공격 방지 추가.
  src/assets/icon/notification/icon-notification-lg.svg
  src/assets/icon/notification/icon-notification-lg.webp
  src/components/common/gnb/GnbActions.tsx
  src/components/notification/NotificationList.tsx
  src/lib/api/notification.api.ts
  src/providers/NotificationSSEProvider.tsx
  src/stores/notificationStore.ts
Labels: 재욱, feat, refactor, priority: high

#334 기사님 찾기 및 상세관련 버그 수정
  src/components/profile/edit/ProfileEditServiceSelection.tsx
  src/components/profile/register/ServiceSelection.tsx
  src/components/searchMover/MoverList.tsx
  src/components/searchMover/[id]/Chip.tsx
  src/components/searchMover/[id]/RequestButton.tsx
  src/constant/profile.ts
  src/lib/api/findMover.api.ts
  src/messages/en.json
  src/messages/ko.json
  src/pageComponents/profile/edit/MoverEditPage.tsx
  src/types/mover.types.ts
Labels: 지연, bug

#344 feat: 기사님 프로필 페이지 CSRF 보안 적용 및 UI 개선
  src/lib/api/user.api.ts
  src/pageComponents/moverMyPage/edit/EditPage.tsx
  src/pageComponents/profile/edit/MoverEditPage.tsx
Labels: 세준, refactor, priority: medium

#343 [#341] refactor : 일반유저 프로필 수정/등록 페이지 최적화
  next.config.ts
  package-lock.json
  package.json
  src/components/common/gnb/Logo.tsx
  src/components/common/gnb/RoleToggle.tsx
  src/components/profile/edit/ProfileEditImageUpload.tsx
  src/lib/api/auth.api.ts
  src/lib/api/user.api.ts
  src/pageComponents/profile/edit/CustomerEditPage.tsx
Labels: 민규, refactor

#345 Fix : 견적 API _ csrf 적용 롤백
  src/lib/api/customerEstimateRequest.api.ts
  src/lib/api/moverEstimate.api.ts
Labels: 수빈, fix, bug

#347 fix : 토큰 재발급 시간 오류 수정
  src/providers/AuthProvider.tsx
Labels: 민규, fix

#350 Fix/estimate request csrf rollback
  src/app/[locale]/(auth)/loading.tsx
  src/app/loading.tsx
  src/lib/api/estimateRequest.client.ts
  src/messages/en.json
  src/messages/ko.json
  src/messages/zh.json
  src/pageComponents/favoriteMover/FavoriteMoverPage.tsx
  src/pageComponents/searchMover/SearchMoverPage.tsx
Labels: 승준, fix, ready for review

#351 fix: 기사님 상세 및 찾기 csrf 롤백
  package-lock.json
  src/assets/icon/clip/icon-clip-md.svg
  src/components/searchMover/FilterBar.tsx
  src/components/searchMover/MoverCard.tsx
  src/components/searchMover/MoverList.tsx
  src/components/searchMover/[id]/DetailInformation.tsx
  src/components/searchMover/[id]/RequestButton.tsx
  src/components/searchMover/[id]/ReviewList.tsx
  src/lib/api/findMover.api.ts
  src/lib/utils/translationUtils.ts
  src/messages/en.json
  src/messages/ko.json
  src/messages/zh.json
  src/pageComponents/searchMover/SearchMoverDetailPage.tsx
  src/pageComponents/searchMover/SearchMoverPage.tsx
  src/types/mover.types.ts
Labels: 지연, fix

#352 fix : 프로필 등록시 유저 정보가 최신화 되지않던 문제 수정 및 프로필 등록 완료 번역 문제 수정
  src/app/[locale]/(auth)/loading.tsx
  src/messages/en.json
  src/messages/ko.json
  src/messages/zh.json
  src/pageComponents/profile/register/CustomerRegisterPage.tsx
  src/pageComponents/profile/register/MoverRegisterPage.tsx
  src/providers/AuthProvider.tsx
Labels: 민규, fix

#355 견적 -기사 받앗던페이지 세부수정
  src/assets/icon/filter/icon-filter-active.svg
  src/assets/icon/filter/icon-filter-inactive.svg
  src/components/estimate/received/SmallFilterSection.tsx
  src/pageComponents/estimate/received/MoverReceivedPage.tsx
Labels: 수빈, feat, fix

#357 fix : 유저 타입에 맞게 로고가 리다이렉트 되도록 수정
  src/components/common/gnb/Logo.tsx
Labels: 민규, fix

#363 [#360] [#361] [#362] [알림] 다국어 기능 구현 및 펄스 효과 추가.
  src/app/globals.css
  src/components/common/gnb/GnbActions.tsx
  src/components/notification/NotificationList.tsx
  src/providers/NotificationSSEProvider.tsx
  src/stores/notificationStore.ts
  src/types/notification.types.ts
Labels: 재욱, refactor, priority: medium

#359 [#234]repactor:견적요청 피드백 반영 및 토스트 알림 색상 변경
  src/app/globals.css
  src/components/estimateRequest/common/EstimateRequestFlow.tsx
  src/components/estimateRequest/common/EstimateRequestLayout.tsx
  src/components/estimateRequest/create/AddressSearchDaum.tsx
  src/components/estimateRequest/create/SpeechBubble.tsx
  src/hooks/useEstimateRequestApi.tsx
  src/hooks/useEstimateRequestForm.tsx
  src/pageComponents/estimateRequest/create/EstimateRequestCreatePage.tsx
  src/pageComponents/estimateRequest/edit/EstimateRequestEditPage.tsx
  src/types/estimateRequest.ts
Labels: 승준, fix, refactor, ready for review

#364 fix:피드백 반영하여 옵티미스틱 반영, 필요시 다음 페이지 자동로드, 시맨틱 태그 사용, 스크린 리더 고려
  src/components/common/button/Favorite.tsx
  src/components/searchMover/MoverCard.tsx
  src/hooks/useMoverData.ts
  src/pageComponents/favoriteMover/FavoriteMoverPage.tsx
Labels: 승준, fix, bug

#368 refactor: 랜딩 & 기사님 찾기 & 기사님 상세 리팩토링
  public/og-image.png
  src/app/layout.tsx
  src/assets/icon/like/icon-like-black.svg
  src/components/searchMover/FavoriteMoverList.tsx
  src/components/searchMover/FilterBar.tsx
  src/components/searchMover/MoverCard.tsx
  src/components/searchMover/MoverList.tsx
  src/components/searchMover/SearchBar.tsx
  src/components/searchMover/SortBar.tsx
  src/components/searchMover/[id]/Chip.tsx
  src/components/searchMover/[id]/DetailInformation.tsx
  src/components/searchMover/[id]/MoverIntro.tsx
  src/components/searchMover/[id]/RequestButton.tsx
  src/components/searchMover/[id]/ReviewAvg.tsx
  src/components/searchMover/[id]/ReviewList.tsx
  src/components/searchMover/[id]/TopBar.tsx
  src/hooks/useMoverData.ts
  src/pageComponents/landing/LadingPage.tsx
  src/pageComponents/searchMover/SearchMoverDetailPage.tsx
  src/pageComponents/searchMover/SearchMoverPage.tsx
Labels: 지연, refactor

#369 refactor : 유저관리 로직 수정
  src/app/[locale]/layout.tsx
  src/app/[locale]/providers.tsx
  src/components/auth/signin/SigninForm.tsx
  src/components/auth/signup/SignupForm.tsx
  src/lib/api/fetcher.api.ts
  src/lib/api/user.api.ts
  src/lib/server/getServerUser.ts
  src/middleware.ts
  src/pageComponents/profile/edit/CustomerEditPage.tsx
  src/pageComponents/profile/register/CustomerRegisterPage.tsx
  src/pageComponents/profile/register/MoverRegisterPage.tsx
  src/providers/AuthProvider.tsx
Labels: 민규, refactor

#370 refactor: 이미지 .svg 변경
  src/assets/icon/like/icon-like-red.svg
  src/assets/icon/like/icon-like-white-lg.svg
  src/components/common/button/Button.tsx
  src/components/common/dropdown/CustomDropdown.tsx
  src/components/common/dropdown/SortDropdown.tsx
  src/components/searchMover/MoverCard.tsx
Labels: 지연, refactor

#372 [공용 컴포넌트] 공용 인풋 컴포넌트 이미지 최적화 - png에서 svg 변경.
  src/assets/icon/etc/icon-visibility-off.png
  src/assets/icon/etc/icon-visibility-off.svg
  src/assets/icon/etc/icon-visibility-on.png
  src/assets/icon/etc/icon-visibility-on.svg
  src/assets/icon/etc/icon-x.png
  src/assets/icon/etc/icon-x.svg
  src/components/common/input/BaseInput.tsx
  src/components/common/input/PasswordInput.tsx
Labels: 재욱, refactor, priority: low

#377 feat : 프로필 이미지 저장 CDN 적용
  next.config.ts
  public/img/etc/profile-upload-skeleton.webp
  public/img/logo/fulllogo.webp
  public/img/logo/logo.webp
  public/img/logo/textlogo.webp
  public/img/mascot/mover-avatartion.webp
  public/img/mascot/profile.webp
  public/img/mascot/user-avatartion.webp
  src/assets/img/logo/fulllogo-lg.png
  src/assets/img/logo/fulllogo-md.png
  src/assets/img/logo/fulllogo-sm.png
  src/assets/img/logo/fulllogo.webp
  src/assets/img/logo/logo-l.png
  src/assets/img/logo/logo-m.png
  src/assets/img/logo/logo-s.png
  src/assets/img/logo/logo.webp
  src/assets/img/logo/textlogo-lg.png
  src/assets/img/logo/textlogo-md.png
  src/assets/img/logo/textlogo-sm.png
  src/assets/img/logo/textlogo-xl.png
  src/assets/img/logo/textlogo.webp
  src/assets/img/mascot/mover-avatartion-lg.png
  src/assets/img/mascot/mover-avatartion.webp
  src/assets/img/mascot/user-avatartion-lg.png
  src/assets/img/mascot/user-avatartion.webp
  src/components/auth/MascotCharacter.tsx
  src/components/auth/signin/SigninHeader.tsx
  src/components/auth/signup/SignupHeader.tsx
  src/components/common/gnb/GnbActions.tsx
  src/components/common/gnb/Logo.tsx
  src/lib/api/user.api.ts
  src/pageComponents/profile/edit/CustomerEditPage.tsx
  src/pageComponents/profile/register/CustomerRegisterPage.tsx
  src/pageComponents/profile/register/MoverRegisterPage.tsx
Labels: 민규, feat

#378 fix : 미들웨어에서 정적파일은 우회되도록 수정
  src/middleware.ts
Labels: 민규, fix

#379 refactor : 유저 상태 관리 수정
  next.config.ts
  src/components/common/input/TextInput.tsx
  src/lib/server/getServerUser.ts
  src/messages/en.json
  src/messages/ko.json
  src/messages/zh.json
  src/providers/AuthProvider.tsx
  src/utils/handleAuthErrorToast.ts
  src/utils/validators.ts
Labels: 민규, refactor

#382 fix:다국어 구조 변경
  src/app/[locale]/review/layout.tsx
  src/components/common/LanguageInitializer.tsx
  src/hooks/useEstimateRequestForm.tsx
  src/i18n/request.ts
  src/middleware.ts
  src/pageComponents/profile/edit/CustomerEditPage.tsx
  src/pageComponents/profile/register/CustomerRegisterPage.tsx
Labels: 승준, fix, ready for review

#383 fix:좋아요 캐싱 즉시 무효화 반영
  src/hooks/useMoverData.ts
Labels: 승준, fix, ready for review

#384 fix:견적요청 캐싱 적용 및 다국어 에러 해결
  src/app/[locale]/estimateRequest/create/page.tsx
  src/app/[locale]/layout.tsx
  src/components/common/LanguageSwitcher.tsx
  src/components/common/gnb/Logo.tsx
  src/components/common/gnb/LogoAndTab.tsx
  src/components/estimateRequest/common/EstimateRequestFlow.tsx
  src/components/estimateRequest/common/EstimateRequestLayout.tsx
  src/components/estimateRequest/create/ProgressBar.tsx
  src/components/estimateRequest/create/SpeechBubble.tsx
  src/components/moverMyPage/schedule/CalendarWithSchedule.tsx
  src/components/searchMover/MoverCard.tsx
  src/components/searchMover/MoverList.tsx
  src/hooks/useEstimateRequestApi.tsx
  src/messages/en.json
  src/messages/ko.json
  src/messages/zh.json
  src/pageComponents/estimateRequest/edit/EstimateRequestEditPage.tsx
  src/pageComponents/review/written/WrittenReviewPage.tsx
Labels: 승준, fix, priority: critical, done

#385 fix : 일반유저 pw 변경 관련 모달 오류 수정
  next.config.ts
  src/lib/api/user.api.ts
  src/messages/en.json
  src/messages/ko.json
  src/messages/zh.json
  src/pageComponents/profile/edit/CustomerEditPage.tsx
  src/pageComponents/profile/register/MoverRegisterPage.tsx
  src/utils/handleAuthErrorToast.ts
Labels: 민규, fix

#387 [#386] chore : 프론트 리드미 초안 작성
  README.md
  public/architecture.png
  public/readmeMain.png
  src/pageComponents/profile/register/CustomerRegisterPage.tsx
Labels: 민규, chore

#388 fix: 필요없는 번들 최적화
  src/app/[locale]/estimateRequest/create/page.tsx
  src/app/layout.tsx
  src/components/estimateRequest/common/EstimateRequestFlow.tsx
  src/components/estimateRequest/common/EstimateRequestStepRenderer.tsx
  src/components/estimateRequest/create/sections/MovingTypeSection.tsx
  src/pageComponents/estimateRequest/create/EstimateRequestCreatePage.tsx
  src/pageComponents/estimateRequest/create/EstimateRequestPage.tsx
  src/utils/shareUtils.ts
Labels: 승준, ready for review

#391 [리뷰] [알림] QA 피드백 반영.
  src/assets/icon/notification/icon-notification.svg
  src/assets/icon/star/icon-star-active-sm.svg
  src/assets/icon/star/icon-star-inactive-sm.svg
  src/components/common/gnb/GnbActions.tsx
  src/components/estimateRequest/(my)/MoverInfo.tsx
  src/components/review/writable/ReviewWriteModal.tsx
  src/components/review/writable/StarRating.tsx
  src/components/review/writable/WritableMoverCard.tsx
  src/components/review/written/WrittenMoverCard.tsx
  src/messages/en.json
  src/messages/ko.json
  src/messages/zh.json
Labels: 재욱, fix, refactor, priority: low

#395 견적- 페이지 시나리오 테스트 피드백 반영
  src/components/common/button/Favorite.tsx
  src/components/estimate/(my)/rejected/[id]/RejectDetailMain.tsx
  src/components/estimate/(my)/request/[id]/RequestDetailMain.tsx
  src/components/estimate/received/ModalChild.tsx
  src/components/estimateRequest/(my)/MoverInfo.tsx
  src/hooks/useLikeToggle.ts
  src/hooks/useMoverData.ts
  src/messages/en.json
  src/messages/ko.json
  src/messages/zh.json
  src/pageComponents/estimate/(my)/rejected/[id]/MoverRejectedDetailPage.tsx
  src/pageComponents/estimateRequest/(my)/pending/UserPendingEstimateRequestPage.tsx
  src/pageComponents/share/SharePage.tsx
  src/utils/apiUtils.ts
Labels: 수빈, fix, refactor

#396 fix : 4차 시나리오 테스트 이슈사항 수정
  src/app/[locale]/(auth)/loading.tsx
  src/app/[locale]/(auth)/moverSignin/page.tsx
  src/app/[locale]/(auth)/moverSignup/page.tsx
  src/app/[locale]/(auth)/userSignin/page.tsx
  src/app/[locale]/(auth)/userSignup/page.tsx
  src/app/[locale]/profile/edit/page.tsx
  src/app/[locale]/profile/register/page.tsx
  src/components/auth/signin/SigninForm.tsx
  src/components/auth/signin/SigninHeader.tsx
  src/components/auth/signup/SignupForm.tsx
  src/components/auth/signup/SignupHeader.tsx
  src/components/common/gnb/SideGnb.tsx
  src/components/common/input/PasswordInput.tsx
  src/components/profile/edit/ProfileEditRegionSelection.tsx
  src/components/profile/register/RegionSelection.tsx
  src/pageComponents/auth/moverSignin/MoverSigninPage.tsx
  src/pageComponents/auth/moverSignup/MoverSignupPage.tsx
  src/pageComponents/auth/userSignin/UserSigninPage.tsx
  src/pageComponents/auth/userSignup/UserSignupPage.tsx
Labels: 민규, fix

#398 bug: 기사님 상세 찜 낙관적 업데이트
  src/hooks/useMoverData.ts
Labels: 지연, bug

#402 fix:하드코딩 삭제
  src/pageComponents/profile/edit/MoverEditPage.tsx
Labels: 세준, fix, priority: medium

#404 Bug/mover
  src/components/common/button/Button.tsx
  src/components/common/button/ShareButton.tsx
  src/components/common/pagination/PaginationButton.tsx
  src/components/searchMover/FilterBar.tsx
  src/components/searchMover/SearchBar.tsx
Labels: 지연, fix, bug

#405 [알림] [리뷰] 코드 마무리
  src/components/notification/NotificationList.tsx
  src/components/review/writable/WritableMoverCard.tsx
  src/components/review/written/WrittenMoverCard.tsx
  src/providers/AuthProvider.tsx
  src/providers/NotificationSSEProvider.tsx
  src/stores/notificationStore.ts
Labels: 재욱, feat, refactor, priority: high

#407 fix: 로컬 포트 삭제
  src/app/[locale]/searchMover/[id]/page.tsx
  src/lib/api/findMover.api.ts
Labels: 지연, fix

#408 [견적] 상세페이지 : 좋아요 버튼 색깔반영
  src/app/[locale]/estimateRequest/(my)/received/page.tsx
  src/components/estimateRequest/(my)/DetailPageMainSeaction.tsx
  src/components/estimateRequest/(my)/LgButtonSection.tsx
  src/components/estimateRequest/(my)/MoverInfo.tsx
  src/components/estimateRequest/(my)/ShareSection.tsx
  src/components/estimateRequest/(my)/received/LastButtonSection.tsx
  src/instrumentation-client.ts
  src/pageComponents/estimateRequest/(my)/received/UserReceivedEstimateRequestPage.tsx
Labels: 수빈, fix

#409 Fix/like button
  src/components/estimateRequest/(my)/LgButtonSection.tsx
  src/components/estimateRequest/(my)/received/LastButtonSection.tsx
  src/pageComponents/estimate/(my)/rejected/MoverRejectedPage.tsx
  src/pageComponents/estimate/(my)/request/MoverRequestPage.tsx
  src/pageComponents/estimate/received/MoverReceivedPage.tsx
  src/pageComponents/estimateRequest/(my)/pending/UserPendingEstimateRequestPage.tsx
  src/pageComponents/estimateRequest/(my)/received/UserReceivedEstimateRequestPage.tsx
Labels: feat
